name: Deploy website
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  dev:
    environment: Dev
    runs-on: ubuntu-latest
    env:
      MY_ENV: ${{ secrets.MY_ENV }}
      ENV: ${{ vars.ENV }}
    steps:
      - name: Failed step
        id: failed_step
        run: echo 1/0
      - name: Continue
        if: steps.failed_step == 'failure'
        run: echo 'Continue'
