name: Deploy website
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  dev:
    environment: Dev
    runs-on: ubuntu-latest
    env:
      MY_ENV: ${{ secrets.MY_ENV }}
      ENV: ${{ vars.ENV }}
    steps:
      - name: Display MY_ENV
        run: |
          echo "$MY_ENV"
          echo "ENV: $ENV"
  test:
    needs: dev
    environment: Test
    runs-on: ubuntu-latest
    env:
      MY_ENV: ${{ secrets.MY_ENV }}
      ENV: ${{ vars.ENV }}
    steps:
      - name: Display MY_ENV
        run: |
          echo "MY_ENV: $MY_ENV"
          echo "ENV: $ENV"
