name: Deploy website
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  dev:
    environment: Dev
    runs-on: ubuntu-latest
    env:
      MY_ENV: ${{ secrets.MY_ENV }}
      ENV: ${{ vars.ENV }}
    steps:
      - name: Prepare
        run: echo "Prepare running reusable component"
  test:
    needs: dev
    uses: ./.github/workflows/sub_workflow.yml
    with:
      my_parameter: MY_PARAMETER
