name: Deploy website
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  dev:
    environment: Dev
    runs-on: ubuntu-latest
    env:
      MY_ENV: ${{ secrets.MY_ENV }}
    steps:
      - name: Display MY_ENV
        run: |
          echo "${{ $MY_ENV }}"
  test:
    needs: dev
    environment: Test
    runs-on: ubuntu-latest
    env:
      MY_ENV: ${{ secrets.MY_ENV }}
    steps:
      - name: Display MY_ENV
        run: |
          echo "${{ $MY_ENV }}"
