name: Test Project
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check event details
        run: echo "${{ toJSON(github.event) }}"
